$font =  Monospace Regular
$textColour = rgba(102, 102, 114, 0.70)

# Date
label {
	monitor =
	text = cmd[update:1000] echo "$(LC_TIME=en_US.UTF-8 date +"%A, %B, %d")"
	color = $textColour
	font_size = 25
	font_family = $font
	position = 0, 350
	halign = center
	valign = center
}

# Time
label {
	monitor =
	text = cmd[update:1000] echo "$(date +"%I:%M")"
	color = $textColour
	font_size = 120
	font_family = $font
	position = 0, 230
	halign = center
	valign = center
}

# Password
input-field {
	monitor =
	size = 280, 55
	outline_thickness = 2
	dots_size = 0.2
	dots_spacing = 0.2
	dots_center = true
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(255, 255, 255, 0.3)
	font_color = rgb(255, 255, 255)
    	fade_on_empty = true
	font_family = $font
    	placeholder_text = <i><span foreground="##ffffff80">Enter Password</span></i>
    	hide_input = false
    	position = 0, -210
    	halign = center
    	valign = center
}

# Background image
background {
	monitor =
	path = ~/.config/hypr/img/lock.jpg
	contrast = 0.8916
	brightness = 0.8172
	vibrancy = 0.1696
	vibrancy_darkness = 0.0
}
